beyondchaos_windows.zip: beyondchaos_ex.exe README custom/**/*
	zip -r beyondchaos_windows.zip beyondchaos_ex.exe README custom
beyondchaos_ex.exe: *.py data/**/* tables/* custom/**/*
	pyinstaller BeyondChaos.py -F -n beyondchaos_ex --add-data tables;tables --add-binary custom\sprites;custom\sprites --add-data "custom\*.txt;custom" --add-data "custom\opera\*.mml;custom\opera" --add-binary "custom\opera\*.bin;custom\opera" --add-data custom\music;custom\music
	mv -f dist\beyondchaos_ex.exe .
	
Updater.exe:
	pyinstaller updater.py -F -n BeyondChaosUpdater